# **IRIS Naive Bayes Classification with Pyspark**

In [1]:
# install
!pip install Pyspark

/bin/bash: /opt/conda/lib/libtinfo.so.6: no version information available (required by /bin/bash)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.4/281.4 MB 3.4 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 kB 13.9 MB/s eta 0:00:00
  Created wheel for Pyspark: filename=pyspark-3.3.2-py2.py3-none-any.whl size=281824024 sha256=5b55dd5e30ef8125db7c29bab394a133db5d9cbec7e06a142c3990efb2e33a45
  Stored in directory: /root/.cache/pip/wheels/07/fb/67/b9f2c0242d156eaa136b45ae4fd99d3e7c0ecc2acfd26f47b9
Successfully built Pyspark
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.7
    Uninstalling py4j-0.10.9.7:
      Successfully uninstalled py4j-0.10.9.7


In [2]:
# start spark session
from pyspark.sql import SparkSession

In [3]:
spark=SparkSession.builder.getOrCreate()

bash: /opt/conda/lib/libtinfo.so.6: no version information available (required by bash)
bash: /opt/conda/lib/libtinfo.so.6: no version information available (required by bash)
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).


23/02/19 13:18:57 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


In [4]:
spark

In [5]:
# read sklearn inbuilt data
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)
iris = iris.frame
iris = spark.createDataFrame(iris)

In [6]:
iris.show()

+-----------------+----------------+-----------------+----------------+------+
|sepal length (cm)|sepal width (cm)|petal length (cm)|petal width (cm)|target|
+-----------------+----------------+-----------------+----------------+------+
|              5.1|             3.5|              1.4|             0.2|     0|
|              4.9|             3.0|              1.4|             0.2|     0|
|              4.7|             3.2|              1.3|             0.2|     0|
|              4.6|             3.1|              1.5|             0.2|     0|
|              5.0|             3.6|              1.4|             0.2|     0|
|              5.4|             3.9|              1.7|             0.4|     0|
|              4.6|             3.4|              1.4|             0.3|     0|
|              5.0|             3.4|              1.5|             0.2|     0|
|              4.4|             2.9|              1.4|             0.2|     0|
|              4.9|             3.1|              1.

In [7]:
iris.printSchema()

root
 |-- sepal length (cm): double (nullable = true)
 |-- sepal width (cm): double (nullable = true)
 |-- petal length (cm): double (nullable = true)
 |-- petal width (cm): double (nullable = true)
 |-- target: long (nullable = true)



In [8]:
iris.columns

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)',
 'target']

In [9]:
from pyspark.ml.feature import VectorAssembler 

In [10]:
featureassembler= VectorAssembler(inputCols=['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)'], outputCol='Features')

In [11]:
output = featureassembler.transform(iris)

In [12]:
output.show()

+-----------------+----------------+-----------------+----------------+------+-----------------+
|sepal length (cm)|sepal width (cm)|petal length (cm)|petal width (cm)|target|         Features|
+-----------------+----------------+-----------------+----------------+------+-----------------+
|              5.1|             3.5|              1.4|             0.2|     0|[5.1,3.5,1.4,0.2]|
|              4.9|             3.0|              1.4|             0.2|     0|[4.9,3.0,1.4,0.2]|
|              4.7|             3.2|              1.3|             0.2|     0|[4.7,3.2,1.3,0.2]|
|              4.6|             3.1|              1.5|             0.2|     0|[4.6,3.1,1.5,0.2]|
|              5.0|             3.6|              1.4|             0.2|     0|[5.0,3.6,1.4,0.2]|
|              5.4|             3.9|              1.7|             0.4|     0|[5.4,3.9,1.7,0.4]|
|              4.6|             3.4|              1.4|             0.3|     0|[4.6,3.4,1.4,0.3]|
|              5.0|           

In [13]:
modeldata=output.select('Features','target')

In [14]:
modeldata.show()

+-----------------+------+
|         Features|target|
+-----------------+------+
|[5.1,3.5,1.4,0.2]|     0|
|[4.9,3.0,1.4,0.2]|     0|
|[4.7,3.2,1.3,0.2]|     0|
|[4.6,3.1,1.5,0.2]|     0|
|[5.0,3.6,1.4,0.2]|     0|
|[5.4,3.9,1.7,0.4]|     0|
|[4.6,3.4,1.4,0.3]|     0|
|[5.0,3.4,1.5,0.2]|     0|
|[4.4,2.9,1.4,0.2]|     0|
|[4.9,3.1,1.5,0.1]|     0|
|[5.4,3.7,1.5,0.2]|     0|
|[4.8,3.4,1.6,0.2]|     0|
|[4.8,3.0,1.4,0.1]|     0|
|[4.3,3.0,1.1,0.1]|     0|
|[5.8,4.0,1.2,0.2]|     0|
|[5.7,4.4,1.5,0.4]|     0|
|[5.4,3.9,1.3,0.4]|     0|
|[5.1,3.5,1.4,0.3]|     0|
|[5.7,3.8,1.7,0.3]|     0|
|[5.1,3.8,1.5,0.3]|     0|
+-----------------+------+
only showing top 20 rows



In [15]:
# split data
train_data,test_data=modeldata.randomSplit([0.8,0.2])

In [16]:
train_data.show()

+-----------------+------+
|         Features|target|
+-----------------+------+
|[4.3,3.0,1.1,0.1]|     0|
|[4.4,2.9,1.4,0.2]|     0|
|[4.6,3.1,1.5,0.2]|     0|
|[4.7,3.2,1.3,0.2]|     0|
|[4.8,3.0,1.4,0.1]|     0|
|[4.8,3.1,1.6,0.2]|     0|
|[4.8,3.4,1.6,0.2]|     0|
|[4.8,3.4,1.9,0.2]|     0|
|[4.9,3.0,1.4,0.2]|     0|
|[4.9,3.1,1.5,0.2]|     0|
|[5.0,3.2,1.2,0.2]|     0|
|[5.0,3.4,1.5,0.2]|     0|
|[5.0,3.4,1.6,0.4]|     0|
|[5.0,3.6,1.4,0.2]|     0|
|[5.1,3.3,1.7,0.5]|     0|
|[5.1,3.5,1.4,0.2]|     0|
|[5.1,3.5,1.4,0.3]|     0|
|[5.1,3.7,1.5,0.4]|     0|
|[5.2,3.5,1.5,0.2]|     0|
|[5.2,4.1,1.5,0.1]|     0|
+-----------------+------+
only showing top 20 rows



In [17]:
# naive bayes model
from pyspark.ml.classification import NaiveBayes

In [18]:
nb = NaiveBayes(featuresCol='Features', labelCol='target')

In [19]:
nb=nb.fit(train_data)

In [20]:
# prediction
y_pred = nb.transform(test_data)

In [21]:
y_pred.show()

+-----------------+------+--------------------+--------------------+----------+
|         Features|target|       rawPrediction|         probability|prediction|
+-----------------+------+--------------------+--------------------+----------+
|[4.6,3.4,1.4,0.3]|     0|[-11.838762802412...|[0.69879008147415...|       0.0|
|[4.6,3.6,1.0,0.2]|     0|[-10.920418016468...|[0.80122012414423...|       0.0|
|[4.7,3.2,1.6,0.2]|     0|[-11.717395792216...|[0.67367687750984...|       0.0|
|[4.9,3.1,1.5,0.1]|     0|[-11.195937214178...|[0.71349088591766...|       0.0|
|[5.0,3.0,1.6,0.2]|     0|[-11.714190432283...|[0.66005175278101...|       0.0|
|[5.1,3.8,1.5,0.3]|     0|[-12.822061409270...|[0.75053077267124...|       0.0|
|[5.2,3.4,1.4,0.2]|     0|[-11.903982628730...|[0.74851111022933...|       0.0|
|[5.7,3.8,1.7,0.3]|     0|[-13.636019982953...|[0.74400835769544...|       0.0|
|[4.4,3.0,1.3,0.2]|     0|[-10.706968296815...|[0.68404690873402...|       0.0|
|[4.4,3.2,1.3,0.2]|     0|[-10.923889381

In [22]:
# confusion matrix
y_pred.groupBy('target', 'prediction').count().show()

+------+----------+-----+
|target|prediction|count|
+------+----------+-----+
|     0|       0.0|   11|
|     1|       1.0|   11|
|     2|       2.0|    9|
|     2|       1.0|    4|
+------+----------+-----+



In [23]:
from sklearn.metrics import confusion_matrix
pred=y_pred.select("prediction").collect()
orig=y_pred.select("target").collect()
print(confusion_matrix(orig, pred))

[[11  0  0]
 [ 0 11  0]
 [ 0  4  9]]


(f1|accuracy|weightedPrecision|weightedRecall|weightedTruePositiveRate| weightedFalsePositiveRate|weightedFMeasure|truePositiveRateByLabel| falsePositiveRateByLabel|precisionByLabel|recallByLabel|fMeasureByLabel| logLoss|hammingLoss)

In [24]:
# evaluation
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

In [25]:
evaluator = MulticlassClassificationEvaluator(
    labelCol='target', predictionCol='prediction')

In [26]:
accuracy = evaluator.evaluate(y_pred)
accuracy

0.884115884115884

In [27]:
# close connection to spark
spark.stop()